# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: send message to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }} 
        args: The ${{ github.event_name }} event triggered first step.    
